# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vu2pqPYA-NRVnTdVZd-vGJKZZEWnijM9
"""

pip install pyshorteners

import pyshorteners

def shorten_url(url):
    s = pyshorteners.Shortener()
    shortened_url = s.tinyurl.short(url)
    return shortened_url

# Example usage
url = input("Enter the URL to shorten: ")
shortened = shorten_url(url)
print(f"Shortened URL: {shortened}")